### ISSUE TITLE
The "Cloud Storage" context menu options are wrongly available for files that haven't finished downloading

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/shield-cloudstorage#39] opened 2018-05-24 12:31 UTC
[Affected versions]:
- Firefox Unbranded 60.0

[Affected Platforms]:
- All Mac
- All Windows

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on your computer.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to "https://www.mozilla.org/en-US/firefox/all/" page.
2. Click any of the "Download" buttons from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar (if needed).
5. Right-click on a file which is currently downloading.
6. Choose the "Move Download To..." > "Dropbox/Google Drive" option and observe the behavior.

[Expected result]:
- The "CloudStorage" context menu options are not available for files that haven't finished downloading.

[Actual result]:
- The "CloudStorage" context menu options are available for files that haven't finished downloading.

[Notes]:
- The `"message": "prompt_move_download_context_menu"` pings are also sent when choosing any option from the "CloudStorage" context menu while the file is downloading.
- Here is a screen recording of the issue: 
![cloudstorage_contextmenu](https://user-images.githubusercontent.com/20083658/40485478-53ce7440-5f67-11e8-93db-9559e70a1e93.gif)

**Comment by punamdahiya** [comment] 2018-05-25 18:10
Updated https://github.com/mozilla/shield-cloudstorage/pull/38 with the fix to explicitly check if download has succeeded before showing Move Download option

**Comment by punamdahiya** [comment] 2018-06-04 17:13
@SoftVision-EmilPasca The fix for the issue is landed in master. Please validate. Thanks!

**Comment by SoftVision-EmilPasca** [comment] 2018-06-05 15:33
I verified this issue on Firefox Unbranded(60.0) and Dev Edition(61.0b7) on Windows 10 x64 and Mac OS 10.13, and the issue is still reproducible, however, with a different scenario.
**[STR]:**
 1. Right-click on a file that has finished downloading.
 2. Right-click on a file that is currently downloading and observe the context-menu.

You can observe that after step 2, the Cloud Storage context menu is available for files which haven't finished downloading.

**[Notes]:**
- Attached a screen-recording of the issue:
![cloudstorage_02](https://user-images.githubusercontent.com/20083658/40986429-d70d1a24-68ee-11e8-9d7a-236b0a313e6d.gif)

**Closed** 2018-06-05 17:45 UTC

**Comment by punamdahiya** [comment] 2018-06-05 17:46
@SoftVision-EmilPasca Thanks for catching this, submitted fix that  hides move download menu item before checking for download completed status. Please validate.

**Comment by SoftVision-EmilPasca** [comment] 2018-06-06 09:15
This issue is no longer reproducible with the latest CloudStorage add-on installed (v1.0.0-06.06.2018), tested this on Windows 10 x64 and Mac 10.13 with the Firefox Unbranded(60.0) and Dev Edition(61.0b7).
