### ISSUE TITLE
Cloud Storage context menu option is not displayed for the items downloaded in the second window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/shield-cloudstorage#18] opened 2018-04-19 11:52 UTC
**[Affected versions]:**
- Latest Nightly 61.0a1

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisites]:**
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Dropbox Cloud is installed on your coputer: https://www.dropbox.com/install
- Google Drive is installed on your computer: https://www.google.com/drive/download/
- Have the CloudStorage add-on installed.

**[Steps to reproduce]:**
1. Start the Nightly browser with the profile from prerequisites and navigate to: https://www.mozilla.org/en-US/firefox/all/ page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the "Download" button from the browser toolbar.
5. Right click on the downloaded file and observe the context menu.
6. Click the "Download" button from the browser toolbar.
7. Right click on the downloaded file and observe the context menu.

**[Expected result]:**

5. The "Move Download To.." context menu option is displayed.
7. The "Move Download To.." context menu option is displayed.

**[Actual result]:**

5. The "Move Download To.." context menu option is displayed.
7. The "Move Download To.." context menu option is not displayed.

**[Notes]:**
- The issue is also reproducible when having only Dropbox or Google Drive installed.
- Attached a screen recording of the issue:
![cloudstorage_contextmenu_options2](https://user-images.githubusercontent.com/20083658/38989860-dcc4bc48-43e0-11e8-8f5d-1980bff1706e.gif)
- The issue is also reproducible when repeating the steps 1-5 in the second window, you can observe the behavior in the second screen recording:
![cloudstorage_contextmenu_options](https://user-images.githubusercontent.com/20083658/38989855-d81f46e0-43e0-11e8-9e4b-e2a805a88ba6.gif)

**Comment by punamdahiya** [comment] 2018-04-19 16:09
@SoftVision-EmilPasca Thanks for finding, will update PR with the fix

**Comment by punamdahiya** [comment] 2018-04-19 21:03
@SoftVision-EmilPasca Updated PR with the fix. Thanks!

**Comment by punamdahiya** [comment] 2018-05-01 20:10
@SoftVision-EmilPasca This issue should be fixed, please check if it's still replicable. Thanks!

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-02 15:26
The issue is no longer reproducible on the latest Cloud Storage build. Tested on Windows 7 x64 and Mac 10.13.

**Closed by SoftVision-CosminMuntean** 2018-05-02 15:26 UTC
