### ISSUE TITLE
Move Download option in context menu seen from Library -> Downloads

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/shield-cloudstorage#17] opened 2018-04-19 11:28 UTC
**[Affected versions]:**
- Latest Nightly 61.0a1

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisites]:**
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Dropbox Cloud is installed on your coputer: https://www.dropbox.com/install
- Google Drive is installed on your computer: https://www.google.com/drive/download/
- Have the CloudStorage add-on installed.

**[Steps to reproduce]:**
1. Start the Nightly browser with the profile from prerequisites and navigate to: https://www.mozilla.org/en-US/firefox/all/ page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar.
5. Right click on the downloaded file and choose the "Google Drive"/"Dropbox" option from the "Move Download To.." context meniu options.
6. Restart the browser and navigate to the "Downloads" panel from the "Overflow Menu".
7. Observe the downloaded items.

**[Expected result]:**

7. The Downloaded items which are moved to "Google Drive"/"Dropbox" downloads folder have the corresponding icon displayed in the top right corner.

**[Actual result]:**

7. The Downloaded items which are moved to "Google Drive"/"Dropbox" downloads folder doesn't have the corresponding icon displayed in the top right corner.

**[Notes]:**
- The issue is also reproducible when having only Dropbox or Google Drive installed.
- The corresponding icon is displayed in the "Library" window (CTRL+J).
- Attached a screen recording of the issue:

![cloudstorage_icon](https://user-images.githubusercontent.com/20083658/38988952-bd7f6016-43dd-11e8-8ae9-a1634f484f65.gif)

**Comment by punamdahiya** [comment] 2018-04-19 16:17
@SoftVision-EmilPasca Download sub view panel accessible from overflow menu is out of scope for this study and doesn't cover cloud storage feature. 
I noticed right click on download item in subview download panel shows 'Move To..' option which it shouldn't, that's a bug and will submit fix in PR.

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-03 13:56
@punamdahiya on the above comment are you referring at the "Downloads" section from the "Library" menu?

If yes,  the issue is still reproducible following the next steps:
1. Start the Nightly browser navigate to https://www.thinkbroadband.com/download page.
2. Download the Extra Small File (5MB) from the page.
3. Click the download button from the browser toolbar.
4. Right click on the downloaded file and observe the "Move Download To..." option.
5. Dismiss the "Download" panel and click the "Library" button from browser toolbar.
6. Click the "Downloads" option and right click on the downloaded file.
7. Observe the context menu.

[Expected Results]:
- The "Move Download To..." option is not available. 

[Actual Results]:
- The "Move Download To..." option is available. 

[Notes]:
- If you don't right click on the downloaded file from the Download panel, the issue is no longer reproducible. See this screen recording: https://goo.gl/n7hRWF
- Here is a screen recording with the issue: https://goo.gl/YKj99Z

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-10 11:38
This issue is still reproducible on the latest Cloud Storage version following the above STR. The "Move Download To..." option is displayed in Library -> Downloads, if you right click on the first downloaded file from Downloads panel and then right click on the downloaded file from Library -> Downloads..

Tested on Windows 7 x64, Mac OS and Ubuntu 16.04 x64.

**Comment by punamdahiya** [comment] 2018-05-11 00:56
@SoftVision-CosminMuntean updated master with fix, to listen popupshowing event on download panel view. Please validate. Thanks!

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-11 09:07
I have retested this issue using the latest Cloud Storage version and the issue is no longer reproducible.
Tested on Firefox 60 unbranded build, Dev Edtition (61.0b3) build and latest Nightly (62.0a1) build on Windows 7 x64, Mac 10.12 adn Ubuntu 16.04.

**Closed by SoftVision-CosminMuntean** 2018-05-11 09:07 UTC
Labels: stretch
